### ISSUE TITLE
FeatureImp not working for classification task?

### ISSUE THREAD

**Issue by MCaraACO** [christophM/iml#102]
Hello @christophM,
We are working on your package, and we are wondering about the outputs of the FeatureImp function in the classification tasks.
Is it normal that this one returns us only 1s for the importance of the variables, whether for all the classes combined or by class? 

(We also tried on the Boston dataset after classifying it. And the FeatureImp function returns 1s for all classes and different outputs for each class.)

####### Dataset generation ######
```
set.seed(1)
random <- data.frame(replicate(5,sample(0:1000,100,rep=TRUE)))
random <- cbind(random,sample(c(1,3,2),100,rep = TRUE))
colnames(random) <- c("A","C","B","D","E","class")
```

######## Verification of the data structure ######
```

res_PCA = PCA(random, quali.sup = 6 )
plot(res_PCA,  habillage = 6)

dta_clusted <- random

summary(dta_clusted)


randomize <- function (dta) {
  random <- runif(nrow(dta)) 
  dta_random <- dta[order(random),]
  return ((dta_random))
}

split <- function(dta){
  prep_dta <- randomize(dta)
  train <- prep_dta[1 : floor(2/3 * nrow(dta)), ]
  test <- prep_dta[ (floor(2/3 * nrow(dta))+1) : nrow(dta), ] 
  return(list(train_set= train, test_set= test))
}

set.seed(1)
a <- split(dta_clusted)

```
######## Train #######
```
train_set <- a$train_set
train_set$class <- as.character(as.factor(train_set$class))
summary(train_set)

X_train <- train_set[which(names(train_set) != "class")]
Y_train <- train_set[which(names(train_set) == "class")]
```

######## Test ########
```
test_set <- a$test_set
test_set$class <- as.character(as.factor(test_set$class))

X_test <- test_set[which(names(test_set) != "class")]
Y_test <- test_set[which(names(test_set) == "class")]

```
#############################################################
```

trControl <- trainControl(method = "cv", number = 10)

fit_model <- caret::train(class ~., 
                          data = train_set,
                          method = "knn", 
                          trControl = trControl,
                          metric = "Accuracy", 
                          tuneGrid = expand.grid(k = 1:nrow(train_set)),
)

fit_model$results
plot(fit_model)

```

#####################   GLOBAL MODEL  ################################### 
```
mod = Predictor$new(model = fit_model, data = dta_clusted, y = "class", type = "prob")

mod$predict(newdata = test_set)

#library(help = "Metrics") => Pour voir toutes les options de critères de perte (loss) possibles 
imp = FeatureImp$new(mod, loss = 'ce')

plot(imp)


```
######## 1 CLASS = 3

```
mod_3 = Predictor$new(model = fit_model, data = dta_clusted[,-ncol(dta_clusted)], y = dta_clusted$class == "3", type = "prob", class = "3")

imp_3 = FeatureImp$new(mod_3, loss = 'ce')

plot(imp_3)

```
######## 1 CLASS = 2

```
mod_2 = Predictor$new(model = fit_model, data = dta_clusted[,-ncol(dta_clusted)], y = dta_clusted$class == "2", type = "prob", class = "2")

imp_2 = FeatureImp$new(mod_2, loss = 'ce')

plot(imp_2)

```
######## 1 CLASS = 1
```

mod_1 = Predictor$new(model = fit_model, data = dta_clusted[,-ncol(dta_clusted)], y = dta_clusted$class == "1", type = "prob", class = "1")

imp_1 = FeatureImp$new(mod_1, loss = 'ce')

plot(imp_1)
```

**Comment by christophM** [comment]
The problem was that the names of the classes did not match so that the classification error was always one.
Fixed now.

**Comment by MCaraACO** [comment]
Hello, thank you for your quick response, unfortunately it does not work better. I tried to change the classes by letters and numbers but nothing helps.

Regards.

Mathias Cara

**Comment by christophM** [comment]
Did you install the the latest iml version with 
`devtools::install_github('christophM/iml')`

**Comment by MCaraACO** [comment]
Yes we have done this but I realize today that it was working well with mean square error criterion but it’s not working with the classification error. 
I did my own algorithm to understand how is processing your FeatureImp function and my function gives me some results with the « ce » criterion it’s why I’m asking you that.

Thank you.

Regards

**Comment by deulofeu1** [comment]
I encountered the same question and wondering if you have solved this problem...
