### ISSUE TITLE
Support for ranger?

### ISSUE THREAD

**Issue by vnijs** [christophM/iml#103]
I'd like to use IML for an upcoming class. However, I'm have trouble using `ranger` with IML. I see some references to ranger in the code base but when using it I get the error below. Any suggestions?

```
library(ranger)
library(iml)
data("Boston", package  = "MASS")
rng = ranger(medv ~ ., data = Boston, num.trees = 50)
X = Boston[which(names(Boston) != "medv")]
predictor = Predictor$new(rng, data = X, y = Boston$medv)
imp = FeatureImp$new(predictor, loss = "mae")

Error in as.data.frame.default(x[[i]], optional = TRUE, stringsAsFactors = stringsAsFactors) : 
  cannot coerce class ‘"ranger.prediction"’ to a data.frame
```

**Comment by bgreenwell** [comment]
You just need to tell **iml** how to obtain predictions from **ranger** models (see the description of the `predict.fun` in `?iml::Predictor`. See below:

```r
library(ranger)
library(iml)
data("Boston", package  = "MASS")
rng = ranger(medv ~ ., data = Boston, num.trees = 50)
X = Boston[which(names(Boston) != "medv")]
pfun <- function(object, newdata) predict(object, data = newdata)$predictions  # <--
predictor = Predictor$new(model = rng, data = X, y = Boston$medv,
                          predict.fun = pfun)
imp = FeatureImp$new(predictor, loss = "mae")
plot(imp)
```
![image](https://user-images.githubusercontent.com/3777755/72154250-281b6000-337e-11ea-982b-4bc236455163.png)

**Comment by christophM** [comment]
I am trying not to have too many custom wrapper in the iml package for ML methods, so as @bgreenwell suggested, using predict.fun is the current best way
