### ISSUE TITLE
How to explain shapley$results output?

### ISSUE THREAD

**Issue by sandeshregmi** [christophM/iml#105]
Hello,
Would it be possible for you to define `phi.var` column values from the shapley$results output? 
Or any literature that explains it please.
Also, `plot(shapley)` doesn't output the difference between Actual and Average prediction. Any help would be appreciated.
Thank you

**Comment by christophM** [comment]
Hi, could you provide a reproducible example? On average, the sum of Shapley values should be the same as the difference between actual and average predictions.
