### ISSUE TITLE
Make iml work with data table inputs

### ISSUE THREAD

**Issue by mllg** [christophM/iml#115]
Here is a small snippet which illustrates the problem:

```r
library(mlr3)
library(mlr3learners)
library(iml)

task = tsk("boston_housing")
train = sample(task$nrow, task$nrow * 2/3)
test = setdiff(seq_len(task$nrow), train)
learner = lrn("regr.ranger")
learner$train(task, train)
newdata = task$data(test, cols = task$feature_names)


# broken
predictor = Predictor$new(learner, data = task$data(train, cols = task$feature_names), y = task$truth(train))
predictor$predict(newdata)

# works
predictor = Predictor$new(learner, data = as.data.frame(task$data(train, cols = task$feature_names)), y = task$truth(train))
predictor$predict(newdata)
```

Simple conversion of user supplied arguments should be sufficient.

**Comment by xiaochi-liu** [comment]
Hello @christophM  and @mllg, I also have questions about how the `iml` can work with `mlr3`.  

The interpretation methods in the `iml` package need the machine learning model to be wrapped in a Predictor object. I was wondering, how to wrap the machine learning model from `mlr3`? Should I input `learner` directly to the `Predictor$new()`? Or should I input `learner$model`? 

The following codes show the difference in Partial Dependence Plots based on different inputs:

``` r
library(mlr3)
library(iml)

task = tsk("iris")
learner = lrn("classif.rpart")

# train a model of this learner for a subset of the task
learner$train(task, row_ids = 1:120)
# this is what the decision tree looks like
learner$model
#> n= 120 
#> 
#> node), split, n, loss, yval, (yprob)
#>       * denotes terminal node
#> 
#> 1) root 120 70 setosa (0.41666667 0.41666667 0.16666667)  
#>   2) Petal.Length< 2.45 50  0 setosa (1.00000000 0.00000000 0.00000000) *
#>   3) Petal.Length>=2.45 70 20 versicolor (0.00000000 0.71428571 0.28571429)  
#>     6) Petal.Length< 4.95 49  1 versicolor (0.00000000 0.97959184 0.02040816) *
#>     7) Petal.Length>=4.95 21  2 virginica (0.00000000 0.09523810 0.90476190) *


# transform data.table to data.frame 
data <- as.data.frame(task$data())

# input the learner directly
class(learner)
#> [1] "LearnerClassifRpart" "LearnerClassif"      "Learner"            
#> [4] "R6"
pred = Predictor$new(learner, data = data)
#> Warning in inferTaskFromModel.Learner(model): Output seems to be class instead of probabilities. 
#>                Automatically transformed to 0 and 1 probabilities.
#>                You might want to set predict.type = 'prob' for Learner!
FeatureEffect$new(pred, "Petal.Length", method = "pdp")$plot()
```

![](https://i.imgur.com/tMdNP4O.png)

``` r

# input the inner model of learner
class(learner$model)
#> [1] "rpart"
pred = Predictor$new(learner$model, data = data)
FeatureEffect$new(pred, "Petal.Length", method = "pdp")$plot()
```

![](https://i.imgur.com/KshMcSQ.png)

<sup>Created on 2020-03-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

As you can see the two Partial Dependence Plots are slightly different, which one is correct?

I want to use `iml` to do the interpretation of machine learning models, and I also like the concise style of `mlr3`. However, I'm not sure whether they are working well with each other currently, thus whether I should transform from `mlr` to `mlr3` in my current project.

**Comment by Lmijnen** [comment]
@mllg did you find a solution yet? I am encountering the same issue!

**Comment by pat-s** [comment]
Can't say when I have time to look into this. It's on the list!

**Comment by mllg** [comment]
Simply converting to data.frame should be enough.

**Comment by xiaochi-liu** [comment]
Thank you very much @mllg.

That's good, just like input `mlr` learner into the `iml` `Predictor$new()` function.

**Comment by Lmijnen** [comment]
@mllg sadly, with data.frame, the importance and interact functions are too computationally intensive to execute for me. Any tips on lowering computational load are welcome. (I have 208 binary features, so I have put the grid.size to 3, which helps a lot already)

**Comment by pat-s** [comment]
@xiaochi-liu Your questions have no relation with this issue - please open a separate issue.

> sadly, with data.frame, the importance and interact functions are too computationally intensive to execute for me. Any tips on lowering computational load are welcome. (I have 208 binary features, so I have put the grid.size to 3, which helps a lot already)


Internally a [data.table](https://github.com/christophM/iml/blob/76b2ff1e3e346d59ea28b45429c6ed362e45086a/R/Data.R#L68-L68) is used so there is no efficiency loss in this regard. 
A grid.size of 3 might not be of help - be careful with this. You should know what the grid.size does and not just adjust it so that computation time gets lowered. 

This is also a different use case issue that has nothing to do with the initial issue here. Please ask on Stackoverflow (preferred for use case questions) or open a new issue :)

**Comment by mllg** [comment]
There still seems to be an issue. Here is an example (from stackoverflow IIRC) where the conversion to a regular data.frame is still required:

```r
library(mlr3)
library(iml) 

data("BostonHousing", package = "mlbench")
task = TaskRegr$new("bh", BostonHousing, target = "medv")
learner = lrn("regr.rpart")
learner$train(task)

X = as.data.frame(task$data(cols = task$feature_names)) # <- here!
y = task$truth()
predictor = Predictor$new(learner$model, data = X, y = y)

effs = FeatureEffects$new(predictor)
plot(effs)
```
