### ISSUE TITLE
Error in FeatureImp when one of the variable names contains "="

### ISSUE THREAD

**Issue by benedikt-mayer** [christophM/iml#128]
the data frame looks like this:
`"x1_b=9", ... "x20_b=0", "y"`

when calling FeatureImp like this:
```R
current.predictor <- Predictor$new(
  model = current.model,
  data = current.chosen_dataset,
  y = "y"
)
current.imp <- FeatureImp$new(current.predictor, loss = "mae", compare = "difference")
```

it throws:
`Error in eval(predvars, data, env) : object 'x1_b=9' not found`

For reference, calling 
`current.predictor$predict(current.chosen_dataset)` 
works just fine

for me, the fix was replacing `=` in the variable names with `_`

**Comment by pat-s** [comment]
Such characters in variable names are known to cause troubles. Thanks for the report, I'll close here and others might find it when searching for the same error.

**Comment by christophM** [comment]
A solution would be to rename the columns

**Comment by benedikt-mayer** [comment]
Thanks for your replies, good to know it's a known issue.

> A solution would be to rename the columns

👍 that was my fix as well / how I found out what the issue is.
