### ISSUE TITLE
How to change theme, title, etc on patchwork plot?

### ISSUE THREAD

**Issue by woodwards** [christophM/iml#135]
Any changes only apply to the last plot. How to change the title, theme etc of the plots?
Or is there some way to extract the plot data in order to make my own plot? I couldn't see anything like this. Thanks!
```
effs <- FeatureEffects$new(predictor, method = "ale")
effs$plot() +
   labs(title = "title") +
   theme_gray()

**Comment by pat-s** [comment]
Try using `*` instead of `+`. See the {patchwork} docs for more info.

**Comment by woodwards** [comment]
Ah cool, I hadn't realised what patchwork was.
