### ISSUE TITLE
Sum of the Shapley values for an individual

### ISSUE THREAD

**Issue by cocotut12** [christophM/iml#140]
Hi 

For an individual, the sum of the shapley values is the difference between the average model output over the training dataset we passed and the prediction for this individual. 
However, using the iml package, I can't find that.

This is an example : 

- Dataset winequality-red.csv : https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/

- Code :
library(tidyr)
library(dplyr)
library("iml")
wine <- read.csv("winequality-red.csv",sep = ';')
set.seed(10) 
sample <- sample.int(n = nrow(wine), size = floor(.80*nrow(wine)), replace = F)
train <- wine[sample, ]
test  <- wine[-sample, ]
Y_train = train$quality
Y_test = test$quality
X_train = train %>%
  select(-quality)
X_test = test %>%
  select(-quality)
#Random forest regression model
library(randomForest)
(model <- randomForest(quality ~ ., data = train, ntree = 50, na.action = na.omit))

- Results 

> mean(predict(model,X_train))
[1] 5.649798

> predict(model,X_train[1:1,])
     491 
5.882333 

> sum(m$phi)
[1] 0.12349

> 5.882333 - 5.649798
[1] 0.232535

**0.232535 != 0.12349**

I don't understand why it's not equal. Is it because of approximations? How can I solve this problem to make local interpretability ?

Sincerely

Corentin

**Comment by christophM** [comment]
Your example is not complete. Could you also provide the code for how you generated the Shapley values?

**Comment by cocotut12** [comment]
I used the functions of the library "iml" :
predictor <- Predictor$new(model , data = X_train, y = Y_train)
m <- Shapley$new(predictor, x.interest = X_train[1:1,])$results

**Comment by christophM** [comment]
Shapley value estimation can be quite unstable. You can increase sample.size in Shapley to get more stable results and closer to the correct difference.
