### ISSUE TITLE
Whish: manually set grid points for PDP or ICE plots

### ISSUE THREAD

**Issue by corneliagru** [christophM/iml#157]
it would be great to have the option to either manually set the grid points or have quantile based grid points for pdp and ice plots. When the data is skewed you need to set a high value for grid size in order to get the desired detail in a very small range, whereas there are way too many grid points in non-relevant areas/ areas with little observations.

**Comment by christophM** [comment]
It's implemented. While I have implemented tests and so on, would be good to get feedback if it does not work properly in any way.

Just install the latest github version:

```R
remotes::install_github("christophM/iml")
``

**Comment by corneliagru** [comment]
Thanks for letting me know! I will check it out and open an issue in case something doesn't work the way it should
