### ISSUE TITLE
Confusing difference in Shapley value

### ISSUE THREAD

**Issue by christophM** [christophM/iml#19]
See https://github.com/christophM/interpretable-ml-book/issues/56

**Comment by expectopatronum** [comment]
I looked at the unrounded values... It's not a mistake/bug, it's just an unfortunate coincidence that the values round like this and then the difference does not add up anymore. Sorry for bringing it up :D
![screen shot 2018-06-22 at 15 39 53](https://user-images.githubusercontent.com/2265475/41779640-c413f50e-7632-11e8-9d7d-55087dae4df0.png)

**Comment by christophM** [comment]
Thanks for doing the detective work!
