### ISSUE TITLE
How to interprete Accumulated Local Effects plot

### ISSUE THREAD

**Issue by xiaochi-liu** [christophM/iml#201]
Hello, the interpretation of the ALE plot confuses me a lot. The [book](https://christophm.github.io/interpretable-ml-book/ale.html#advantages-6) says

>  ALE plots are centered at zero.This makes their interpretation nice, because the value at each point of the ALE curve is the difference to the mean prediction.

May I ask, what does this `mean prediction` refer to specifically? Is it just the average of the model's predicted values?

Your kind guidance is much appreciated!

**Comment by christophM** [comment]
Yes, the mean prediction is the average over the predictions. So a value of +1 of an ALE curve is relative to this mean prediction.

**Comment by xiaochi-liu** [comment]
Got it. Thank you so much @christophM!
