### ISSUE TITLE
lime package vs iml

### ISSUE THREAD

**Issue by andreysharapov** [christophM/iml#51]
Hi Christoph

I wonder why results obtained using lime package and iml are different.

lime.explain = LocalModel$new(predictor, x.interest = X_test[1,], k = 5)
lime.explain$results
plot(lime.explain)

 vs.

explainer <- lime(X_train, model)
explanation <- lime::explain(X_test[1,], explainer, n_features = 5)
plot_features(explanation)

Thanks

**Comment by christophM** [comment]
Could you expand the example above to be reproducible?
