### ISSUE TITLE
iml methods not working with xgboost

### ISSUE THREAD

**Issue by juliafried** [christophM/iml#54]
Minimalbsp:

```
library(mlr)
library(iml)

# files on slack!!
load("titanic.rda") 
source("mylearnerxgboost.R")

titanic$Survived = as.numeric(titanic$Survived)

task = makeRegrTask(data = titanic, target = "Survived")
lrn = makeLearner("regr.xgboost.mod")
lrn = makeLearner("regr.randomForest")
mod = train(lrn, task)

x = titanic[which(names(titanic) != "Survived")]
p = Predictor$new(mod, x, y = titanic$Survived)

pdp = FeatureEffect$new(p, "Sex", method = "pdp")
plot(pdp)
```

**Comment by scholbeck** [comment]
I'm having the same problem.
`xgboost` needs a matrix to work with but `iml` requests a data.frame:

`library(mlr)`
`library(iml)`
`bh.data = getTaskData(bh.task)`
`bh.data = createDummyFeatures(bh.data)`
`tsk = makeRegrTask(data = bh.data, target = "medv")`
`mod = train("regr.xgboost", tsk)`
`bh.matrix = as.matrix(bh.data)`
`predict(mod$learner.model, bh.matrix[, !colnames(bh.matrix) %in% "medv"])`


`predictor = Predictor$new(mod$learner.model, data = bh.matrix, y = bh.data$medv)`

Console output:
`Assertion on 'X' failed: Must be of type 'data.frame', not 'matrix'.`

**Comment by christophM** [comment]
See #29
