### ISSUE TITLE
Show predicted value in title of Shapley and LocalModel plot

### ISSUE THREAD

**Issue by christophM** [christophM/iml#59]
Write in the title for LocalModel:

Prediction: X
Prediction (local): 

For Shapley:

Prediction: X
Difference to average prediction: X

**Comment by samuelreuther** [comment]
I wonder how could I extract in "LocalModel" the value of "LocalModel prediction"? (I could not find this value in the LocalModel-object anywhere.)

**Comment by christophM** [comment]
You can call the predict function:

`r
local = LocalModel$new(pred, x.interest)
local$predict(x.interest)
`

**Comment by samuelreuther** [comment]
That's it, thank you very much!
