### ISSUE TITLE
Documentation for custom predict function

### ISSUE THREAD

**Issue by j-hartshorn** [christophM/iml#62]
Hi Christoph,

The line in the docs for Predictor, for a custom predict function, is:

> predict.fun: (function) The function to predict newdata. Only needed if model is not a model from mlr or caret package.

I think it should probably say that the function needs to have the signature `predict(model, newdata)`. I couldn't find this in the docs and had to work this out from a tutorial online.

Similarly, I think it would be helpful if the options for `class` and `type` were listed, and even better if they were elaborated upon.

Thanks for creating such a great package!

**Comment by christophM** [comment]
Good point! Thanks
