### ISSUE TITLE
Required Dependencies

### ISSUE THREAD

**Issue by PietroTurati** [christophM/iml#78]
Hi Christoph,

Thank you for sharing your work.
What are the need in terms of R version.
I have tried to run it on the R 3. 4  and it seems to run into a failure due to the package mvtnorm not supported on version previous to 3.4.4
Is that package really necessary ?

Thanks in advance,

**Comment by christophM** [comment]
The dependency on mvtnorm comes from the dependency of iml on partykit. Since partykit is only used for the surrogate models, I moved it to "Suggests" and now the other function in iml should work without requiring mvtnorm.
