### ISSUE TITLE
FeatureEffect error for method = "ale" when predictors contain NA

### ISSUE THREAD

**Issue by kransom14** [christophM/iml#80]
I receive a warning message when I calculate FeatureEffect$new using a dataset that contains NAs: Warning message:
In ((.y.hat.cumsum[1:(nrow(.SD) - 1)] + .y.hat.cumsum[2:nrow(.SD)])/2) *  :
  longer object length is not a multiple of shorter object length

Then ale$plot() gives the following error: 
Error in if (params$width > 0) function(x) jitter(x, amount = params$width) : 
  missing value where TRUE/FALSE needed

Reproducible example below. Dataset comes from the breakDown package. 
```
library(iml)
library(gbm)
library(breakDown)
library(missForest)
library(tidyverse)

wine_na <- prodNA(wine %>% select(-fixed.acidity), 0.1)
wine_na$fixed.acidity <- wine$fixed.acidity

m <- gbm(fixed.acidity ~ ., data = wine, distribution = "gaussian")

pred <- function(model, newdata, n.trees)  {
  results <- predict(model, newdata, n.trees = m$n.trees)
  return(results)
}

mod <- Predictor$new(model = m, data = wine %>% select(-fixed.acidity), predict.fun = pred)

ale <- FeatureEffect$new(mod, feature = "alcohol")
ale$plot()

# use dataset with NAs

m <- gbm(fixed.acidity ~ ., data = wine_na, distribution = "gaussian")

mod <- Predictor$new(model = m, data = wine_na %>% select(-fixed.acidity), predict.fun = pred)

ale <- FeatureEffect$new(mod, feature = "alcohol")
ale$plot()
```

**Comment by christophM** [comment]
NAs are not supported. All the interpretation methods, also ALE, require data without missing values.

**Comment by christophM** [comment]
I guess a more informative error message would be meaningful.

**Comment by christophM** [comment]
TODO: 
When the Predictor object is constructed, check if any value is NA.
If there are NAs, return an error that the Data should not contain NAs.
Also, add a test to test this behavior

**Comment by schwa021** [comment]
I know this is closed - but I am confused about something.

The answer says that NA are not handled - but if I look in the results slot of the ale object, things look correct. It seems that only the plotting function is the problem.
