### ISSUE TITLE
make the iml package compatible with glmnet models

### ISSUE THREAD

**Issue by lcrmorin** [christophM/iml#83]
Glmnet is a powerfull yet simple R package to fit regularized models. As-is the glmnet model works on data-matrices (model.matrix) and output an ensemble of models for varying lambdas. It would be very awsome to make the iml package compatible with this data form and with the possibility to specify the lambda to use glmnet models.

**Comment by christophM** [comment]
There are just to many packages for which I would have to write and maintain wrappers. 

A good workaround is to use mlr:

`makeLearner("regr.glmnet")`
