### ISSUE TITLE
Number of parallel processes

### ISSUE THREAD

**Issue by Katan5555** [christophM/iml#86]
It seems that the default Number of parallel processes is all available. Is there a way to manually select this in the function ?

**Comment by christophM** [comment]
You have to set the number of processes outside of iml package. See an example here: https://cran.r-project.org/web/packages/iml/vignettes/parallel.html

**Comment by Katan5555** [comment]
Thanks, but for now, the option "parallel = TRUE" is not available.

Error in .subset2(public_bind_env, "initialize")(...) : 
  unused argument (parallel = TRUE)
Timing stopped at: 0 0 0
