### ISSUE TITLE
iml::Interaction$new() feature name errors when using features with spaces in their names

### ISSUE THREAD

**Issue by evilantal** [christophM/iml#88]
I'm having issues using iml::Interaction$new() when there are features present in the model and dataset that have spaces in their column names.
In my case these spaces are the result of using model.matrix() to one-hot encode the dataset for training a glm and xgboost model, but can occur in any other manner.
Here's some basic code that reproduces the problem:

```
x<-data.frame(y=rnorm(100),feat1=c("Word","Word two","Word three","Word four"),feat2=rnorm(100))
x.m<-as.data.frame(model.matrix(y~.,data=x))[,-1] #[,-1] to remove the (Intercept) column
mod<-glm(y~.,data=cbind(y=x$y,x.m))

pred<-function(model,newdata) {
  results<-as.data.frame(predict(model,newdata))
  return(results[[1L]])
}

library(iml)
predictor<-Predictor$new(model=mod,data=x.m,y=x$y,predict.fun=pred)
interact<-Interaction$new(predictor) # here, the error is thrown

# inspect features used in the model and column names in the dataset
names(x.m)
mod$terms
```

As you can see, the function probably gets confused by the "`" characters used in the predvars attribute of the model for feature names with spaces in them.
Doing a normal 

```predict(mod,newdata=x.m) ```

works as expected.

**Comment by christophM** [comment]
See https://github.com/christophM/iml/pull/94
