### ISSUE TITLE
Interactive Plot with Plotly - Compatability

### ISSUE THREAD

**Issue by mdancho84** [christophM/iml#89]
Hi Chris,

Great R package. IML is very well done. 

I'd like to request a small tweak to the plotting functionality so that expressions (like y-hat) are optional. 

I'm creating a PDP Plot, and trying to make interactive with the `plotly` library using `ggplotly()`. I'm running into an issue because of the y-hat uses an `expression()`. 

```
> ggplotly(g1)
Error in unique.default(x) : 
  unimplemented type 'expression' in 'HashTableSetup'
```

I checked and found that `plotly` does not support expressions. Maybe include an option to just use `"y-hat"` instead of `hat(y)` in the plotting functions should do the trick.

**Comment by ugroempi** [comment]
Hi Matt,
I ran into a similar problem, wanting to change axis labels, and finding that `ylab` or `labs` does not work on ALE plots. I found a solution by checking the code of function `FeatureEffect`: the axis label is added with `scale_y_continuous` and therefore has to be modified in the same way. With **ggplot2** loaded, you can replace the unwanted y-hat by an axis label of your liking, using 

`g1 + scale_y_continuous(name="your label")`

Best, Ulrike

**Comment by christophM** [comment]
Didn't know that expression has problem with ggplotly. Maybe it's best to remove the expression and replace it with "yhat".
